#!/bin/sh
#
# Configuring host communication.
#
  
case "$1" in
  start)
	printf "Configuring host communication."
	
	sleep 3
  	
  	/sbin/ifconfig eth0 192.168.15.15 up
  	/sbin/route add -host 192.168.15.1 dev eth0
  	/sbin/route add default gw 192.168.15.1
  	[ $? = 0 ] && echo "OK" || echo "FAIL"
  	;;
    stop)
  	printf "Shutdown host communication. "
  	/sbin/route del default
  	/sbin/ifdown -a
  	[ $? = 0 ] && echo "OK" || echo "FAIL"
  	;;
    restart|reload)
  	"$0" stop
  	"$0" start
  	;;
    *)
  	echo "Usage: $0 {start|stop|restart}"
  	exit 1
esac
  
exit $?
